apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
  namespace: ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: ci-cd-app
        image: docker.io/svelaga2704/ci-cd-demo:latest
        imagePullPolicy: Always   # 🔑 Always pull the newest image
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-service
  namespace: ci
spec:
  selector:
    app: ci-cd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort   # Or LoadBalancer if using cloud
