apiVersion: v1
kind: Pod
metadata:
  name: jenkins-kaniko
  namespace: ci
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--context=git://github.com/svelaga2704/CI-CD-Pipeline-jenkins_Kubernetes_Helm_Automation.git#main"
      - "--dockerfile=Dockerfile.dockerfile"
      - "--destination=docker.io/svelaga2704/ci-cd-demo:latest"
      - "--verbosity=debug"
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker/
        readOnly: true
  restartPolicy: Never
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
        items:
          - key: .dockerconfigjson
            path: config.json
