apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: ci
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--dockerfile=/workspace/Dockerfile.dockerfile"
      - "--context=dir:///workspace/"
      - "--destination=svelaga2704/ci-cd-demo:latest"
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockerhub-secret
