apiVersion: v1
kind: Pod
metadata:
  name: jenkins-kaniko
  namespace: ci
  labels:
    jenkins/jenkins-jenkins-agent: "true"
spec:
  serviceAccountName: default
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:3327.v868139a_d00e0-8
    args: ["$(JENKINS_SECRET)", "$(JENKINS_NAME)"]
    env:
    - name: JENKINS_URL
      value: "http://jenkins.ci.svc.cluster.local:8080/"
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
      readOnly: true
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockerhub-secret
